# Numpy
1.0 Numpy ndarray
2.0 array operations
3.0 staistical methords
4.0 Matrix class

In [4]:
#Import Numpy
import numpy as np
data=[[2,6,1,3,7],[5,10,4,9,8]]
data=np.array(data)
print (data)

[[ 2  6  1  3  7]
 [ 5 10  4  9  8]]


In [8]:
#this will get us thye number of raws and columns of the array
print (data.shape)

(2, 5)


In [12]:
#produce an array of 0's
print (np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
#produce an array of 1's
print (np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#creating an array in the range of 30
array=np.arange(30)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [16]:
# access array element from index 5 to 12
print(array[5:12])

[ 5  6  7  8  9 10 11]


In [17]:
#replacing the array element from index 6 to 16 with 0
array[6:16]=0
print(array)

[ 0  1  2  3  4  5  0  0  0  0  0  0  0  0  0  0 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


# Array Operations

In [25]:
#arithmetic Operations
data= np.array([[5,6,7],[8,9,10]])
print (data)

[[ 5  6  7]
 [ 8  9 10]]


In [26]:
#substaract 3 from all data elements
print(data- 3)

[[2 3 4]
 [5 6 7]]


In [27]:
#add 5 to all array elements
print (data +5)

[[10 11 12]
 [13 14 15]]


In [28]:
# squares all the array elements
print(data*data)

[[ 25  36  49]
 [ 64  81 100]]


In [30]:
# transposing and swapping
data=np.arange(16).reshape((4,4))
print(data)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [33]:
print(data.T)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [34]:
x=np.random.randn(2,3)
print(x)

[[-0.61284242 -0.5440671   0.17377335]
 [-0.79177366 -2.23990243  1.35732413]]


# statistical methords

In [35]:
#
data= np.arange(30)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [37]:
print(data.mean())

14.5


In [39]:
print(data.max())

29


In [41]:
print(data.min())

0


# matrix class

In [47]:
x=np.random.randn(2,3)
x=np.matrix(x)
y=np.random.randn(3,2)
y=np.matrix(y)
#multiply the matrices
print(x*y)

[[2.92414272 3.12204409]
 [3.02748012 4.4154959 ]]
